### ISSUE TITLE
Error - Raspberry Pi 3b

### ISSUE THREAD

**Issue by Ulysses-101** [ShawnDEvans/smbmap#41] opened 2020-01-17 14:55 UTC
I get the following error when I try to run smbmap:

Traceback (most recent call last):
  File "./smbmap.py", line 19, in <module>
    from impacket import version, smbserver
  File "/usr/local/lib/python3.5/dist-packages/impacket/smbserver.py", line 48, in <module>
    from impacket import smb, nmb, ntlm, uuid
  File "/usr/local/lib/python3.5/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
ImportError: cannot import name 'noValue'

I have tried removing/reinstalling impacket and pyasn1 but to no avail. 

Any help would be greatly appreciated. 

Thanks.

**Comment by ShawnDEvans** [comment] 2020-01-17 16:45
On it! Thanks for letting me know.

**Comment by ShawnDEvans** [comment] 2020-02-17 16:51
I think this was related to the incorrect version of Impacket. Going to close it for now, I'm not able to reproduce. Update Impacket and let me know if it persists.

**Closed by ShawnDEvans** 2020-02-17 16:51 UTC
