### ISSUE TITLE
Authentication error (yes, me too...)

### ISSUE THREAD

**Issue by frroool** [ShawnDEvans/smbmap#52] opened 2020-05-03 20:06 UTC
Hi!

Got some of the authentication errors that it seems like other people have had too and I can not fix it.

### smbmap
```sh
kali@kali:~/smbmap$ python3 smbmap.py -H 10.10.10.178
[!] Authentication error on 10.10.10.178
```
```sh
kali@kali:~/smbmap$ python3 smbmap.py -H 10.10.10.178 -u '' -p ''
[!] Authentication error on 10.10.10.178
```
```sh
kali@kali:~$ smbmap -H 10.10.10.178
[!] Authentication error on 10.10.10.178
```
```sh
kali@kali:~$ smbmap -H 10.10.10.178 -u '' -p ''
[!] Authentication error on 10.10.10.178
```
### smbclient
```sh
kali@kali:~$ smbclient -N -L 10.10.10.178

        Sharename       Type      Comment
        ---------       ----      -------
        ADMIN$          Disk      Remote Admin
        C$              Disk      Default share
        Data            Disk      
        IPC$            IPC       Remote IPC
        Secure$         Disk      
        Users           Disk      
SMB1 disabled -- no workgroup available
```

Any tips?

**Comment by ShawnDEvans** [comment] 2020-05-03 20:11
Rats! I'm guessing you cloned the latest greatest?

**Comment by frroool** [comment] 2020-05-04 06:39
> Rats! I'm guessing you cloned the latest greatest?

Sure did!

**Comment by ShawnDEvans** [comment] 2020-05-04 16:06
I managed to setup a test environment and reproduce the same result! I'm on it! I'll keep you posted. Thanks for the feedback!

**Comment by ShawnDEvans** [comment] 2020-05-04 17:31
OK - I think I fixed the issue. Windows apparently wanted a non zero length string for a password. I made the default a space, which seemed to eliminate the error. This may cause other issues, but as far as I can tell based on a few Linux boxes I tested it against a  NULL username and any password does the trick. 

Let me know if this works for you, and we can close this out! Thanks again!

**Comment by gitmopp** [comment] 2020-05-06 07:06
I have the same problem with KALI Linux (2020.2), it worked with KALI Linux with updates from 2020-03-31, after the update yesterday it stopped working.
So it seems to be related to one of the python libraries.

**Comment by gitmopp** [comment] 2020-05-06 09:20
I checked the code and added the following line to 574 (maybe you can also add it to your code)
`print('SMB Login Error:', e)`
When I run the script I get the following error:
`SMB Login Error: Missing required parameter 'digestmod'.`

**Comment by gitmopp** [comment] 2020-05-06 09:22
It is related to this problem [https://github.com/SecureAuthCorp/impacket/issues/702](url)

**Comment by gitmopp** [comment] 2020-05-06 09:34
I updated to impacket-0.9.21 and it works again.

**Comment by ShawnDEvans** [comment] 2020-05-06 12:50
Closing this one. I think it should be good to go.

**Closed by ShawnDEvans** 2020-05-06 12:50 UTC
